apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: usama8pixel/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: usama8pixel/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: '**/*.js'
          dest: .
    - image: usama8pixel/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
    - image: usama8pixel/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
    - image: usama8pixel/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
    - image: usama8pixel/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .