apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo # using this app uder the selector,
      # the deployment is going to find the pods that it creates
  template:
    metadata:
      labels:
        app: orders-mongo # and this is going to be a label that gets applied to the pod
    spec:
      containers:
        - name: orders-mongo # the name of the container
          image: mongo # the image name, this comes from the dockerhub automatically
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    app: orders-mongo # this says that find the pods with the name auth-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017